// <auto-generated />
using Infrastructure.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations.MainDb
{
    [DbContext(typeof(MainDbContext))]
    partial class MainDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("Domain.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Descending")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Game");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descending = true,
                            Title = "Snake Game"
                        },
                        new
                        {
                            Id = 2,
                            Descending = true,
                            Title = "Tetris"
                        },
                        new
                        {
                            Id = 3,
                            Descending = true,
                            Title = "Ball Shooting"
                        },
                        new
                        {
                            Id = 4,
                            Descending = true,
                            Title = "Memory"
                        },
                        new
                        {
                            Id = 5,
                            Descending = false,
                            Title = "15 Puzzle"
                        },
                        new
                        {
                            Id = 6,
                            Descending = true,
                            Title = "Brick Breakout"
                        },
                        new
                        {
                            Id = 7,
                            Descending = false,
                            Title = "Mine Sweeper"
                        });
                });

            modelBuilder.Entity("Domain.Models.ScoreHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ScoreHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
